# Generated by Django 3.2.9 on 2022-02-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0002_coments'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='my_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
